### ISSUE TITLE
Presence Doesn't appear

### ISSUE THREAD

**Issue by Benjamin2722** [jtpox/discord-presence-roon#20]
Not sure if I'm just doing this wrong or if something is outdated... but just simply put it does show up on discord

**Comment by jtpox** [comment]
Sorry for taking a bit. https://github.com/jtpox/discord-presence-roon/commit/42356f1c3ce7221fc153d586bc5fb4041bcc524c Should fix it.

**Comment by Benjamin2722** [comment]
hm... maybe its me. I think I have the client ID right? I'm not sure tbh why its still not appearing

**Comment by Benjamin2722** [comment]
lemme reinstal it

**Comment by jtpox** [comment]
Is your "Activity Status" enabled in your Discord settings?

**Comment by Benjamin2722** [comment]
yeah.. I redownloaded and same thing, should I upload a log of what the terminal says?

**Comment by jtpox** [comment]
Yes, that would help. And did you also enable the extension in Roon's settings? You also have to put your devices' names in the "Zones to Monitor" field.

**Comment by Benjamin2722** [comment]
that is probably it... what does that mean "my devices' names" exactly? like what my PC would show up as on bluetotth and stuff? or something else
I did enable the extension though yes

**Comment by Benjamin2722** [comment]
I left it to what it has when you download it, "Desktop,Living Room"

**Comment by jtpox** [comment]
You have to change it to what you have named your audio devices in Roon.

**Comment by Benjamin2722** [comment]
yes! thank you!! it works. Sorry for the trouble

**Comment by jtpox** [comment]
No problem
